const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
const CONTACT_US_REQUEST_FAILURE = "CONTACT_US_REQUEST_FAILURE";
const CONTACT_US_REQUEST_SUCCESS = "CONTACT_US_REQUEST_SUCCESS";

export {
  CONTACT_US_REQUEST,
  CONTACT_US_REQUEST_FAILURE,
  CONTACT_US_REQUEST_SUCCESS,
};
