const SAVE_USER_LOGIN_DATA = "SAVE_USER_LOGIN_DATA";
const SAVE_USER_LOGIN_DATA_SUCCESS = "SAVE_USER_LOGIN_DATA_SUCCESS";
const SAVE_USER_LOGIN_DATA_FAIL = "SAVE_USER_LOGIN_DATA_FAIL";
const USER_LOGOUT = "USER_LOGOUT";

export {
  SAVE_USER_LOGIN_DATA,
  SAVE_USER_LOGIN_DATA_FAIL,
  SAVE_USER_LOGIN_DATA_SUCCESS,
  USER_LOGOUT,
};
